### ISSUE TITLE
Project specification

### ISSUE THREAD

**Issue by vladaindjic** [dotun-ogundare/tourists-hub-serbia#5]
Hi all, @dotun-ogundare 

I think the easiest way to continue communication is via GitHub issues, so we'll have everything about technical stuff in one place.

I've checked out the project specification, and it looks good so far. Since I couldn't find many details about functionalities, I'd like to check whether you're planning to implement what I proposed [here](https://github.com/vladaindjic/SCM-exchange-students/blob/master/SPEC.md)?

The workflow looks good (more than we're demanding for the course purposes). What I'd like to see is more containers orchestrated by the docker-compose. As you may find [here](https://github.com/vladaindjic/SCM-exchange-students#the-project-specification), you should provide at least the four containers plus one for the angular client (in your case). 

Also, you need to provide both unit and integration tests (6 points). Please note the [git and GitHub usage items](https://github.com/vladaindjic/SCM-exchange-students#the-project-specification) since they value 20 points together. Also, submit the class diagram that describes the model of your applications (6 points).

Just check [the project specification](https://github.com/vladaindjic/SCM-exchange-students#the-project-specification) and [the web application description](https://github.com/vladaindjic/SCM-exchange-students/blob/master/SPEC.md) once again before starting with the implementation.

Let me know if you need any help!

Best,
Vladimir

**Comment by dotun-ogundare** [comment]
Yes sir, we are planning to implement all that you have proposed. I will edit project specification to add details on functionalities. 

We will implement the containers and the orchestration as indicated. We will also edit the project specification to be more elaborate of the project architecture and implementation strategy.

We will provide both unit and integration tests and we have also noted other things you indicated. 

Thank you.
Dotun

**Comment by dotun-ogundare** [comment]
Dear Prof @vladaindjic ,

I just wanted to let you know that we are making progress. We have been working on the angular frontend with VS code which is completely detached from the backend built with IntelliJ. I will however put the frontend folder in the backend folder and push it this week.  Thanks

**Comment by vladaindjic** [comment]
Glad to hear that. :)
